volumes:
  cooper-db:
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cooper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - cooper-db:/var/lib/postgresql/data
    networks:
      - cooper_dependencies
networks:
  cooper_dependencies:
    driver: bridge
