volumes:
  cloudviz-db:
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cloudviz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - cloudviz-db:/var/lib/postgresql/data
    networks:
      - cloudviz_dependencies
networks:
  cloudviz_dependencies:
    driver: bridge

