services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cooper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - cooper-db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - cooper_dependencies
    restart: always

  postgrest:
    image: postgrest/postgrest:latest
    environment:
      PGRST_DB_URI: postgres://postgres:password@postgres:5432/cooper
      PGRST_DB_SCHEMA: public
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000
      PGRST_DB_ANON_ROLE: postgres
    ports:
      - 8080:3000
    networks:
      - cooper_dependencies
    restart: always
    depends_on:
      - postgres

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8081:8080
    expose:
      - 8080
    environment:
    # Tell Swagger to document the postgrest API
      API_URL: http://localhost:8080/

networks:
  cooper_dependencies:
    driver: bridge

volumes:
  cooper-db:
