name: Publish to Maven Central

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Install gpg
        run: |
          sudo apt-get update
          sudo apt-get install -y gpg
          
      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          
      - name: Publish to Maven Central
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          mvn clean deploy -P release \
            -Dgpg.passphrase="$GPG_PASSPHRASE" \
            -Dgpg.keyname="$GPG_KEY_ID" \
            -Dsonatype.username="$SONATYPE_USERNAME" \
            -Dsonatype.password="$SONATYPE_PASSWORD" \
            -Dsonatype.serverId=central \
            -Dsonatype.nexusUrl=https://s01.oss.sonatype.org/ \
            -Dsonatype.repositoryId=central